### ISSUE TITLE
UserWarning: Metadata Warning, tag 34853 had too many entries: 0, expected 1 / IndexError: tuple index out of range

### ISSUE THREAD

**Issue by tomholub** [seisvelas/S3-Exif-Cleaner#4]
See the following:

```
/home/luke/.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:594: UserWarning: Metadata Warning, tag 34853 had too many entries: 0, expected 1
  % (tag, len(values))
Traceback (most recent call last):
  File "/home/luke/.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 589, in _setitem
    (dest[tag],) = values
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "s3_cleanse.py", line 53, in <module>
    img_ops = ImageOps.exif_transpose(img_ops)
  File "/home/luke/.local/lib/python3.6/site-packages/PIL/ImageOps.py", line 549, in exif_transpose
    transposed_image.info["exif"] = exif.tobytes()
  File "/home/luke/.local/lib/python3.6/site-packages/PIL/Image.py", line 3336, in tobytes
    ifd[tag] = value
  File "/home/luke/.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 524, in __setitem__
    self._setitem(tag, value, self.legacy_api)
  File "/home/luke/.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 596, in _setitem
    dest[tag] = values[0]
IndexError: tuple index out of range

```

**Comment by seisvelas** [comment]
This is a bug on old(er) versions of Pillow. I've updated requirements.txt to specify a version of Pillow that doesn't suffer from this problem. Here is how I recreated this bug using an old version of Pillow, and then fixed it by upgrading Pillow:

```
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ cat test.py
from PIL import Image, ImageOps

img_ops = Image.open('odd.jpg')
ImageOps.exif_transpose(img_ops)

alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ # Install old version of Pillow
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ pip3 install Pillow==7.0.0
Requirement already satisfied: Pillow==7.0.0 in /home/alex/.local/lib/python3.8/site-packages (7.0.0)
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ python3 test.py
/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 282 had too many entries: 2, expected 1
  warnings.warn(
/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  warnings.warn(
/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 34853 had too many entries: 0, expected 1
  warnings.warn(
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 585, in _setitem
    (dest[tag],) = values
ValueError: not enough values to unpack (expected 1, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    ImageOps.exif_transpose(img_ops)
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/ImageOps.py", line 549, in exif_transpose
    transposed_image.info["exif"] = exif.tobytes()
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/Image.py", line 3257, in tobytes
    ifd[tag] = value
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 523, in __setitem__
    self._setitem(tag, value, self.legacy_api)
  File "/home/alex/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 592, in _setitem
    dest[tag] = values[0]
IndexError: tuple index out of range
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ # Now the same thing with a newer version of Pillow
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ pip3 install Pillow==8.1.1
Collecting Pillow==8.1.1
  Downloading Pillow-8.1.1-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 2.0 MB/s
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 7.0.0
    Uninstalling Pillow-7.0.0:
      Successfully uninstalled Pillow-7.0.0
Successfully installed Pillow-8.1.1
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ python3 test.py
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ echo $?
0
alex@UbuntuAMD:~/Code/FlowCrypt_Experiments$ # Ran successfully!
```

To confirm that this is likely the cause in your case, could you tell me what version of Pillow you currently have (via the command `pip3 show Pillow`)?

If you do indeed have an older version, you can upgrade to the new version specified in requirements.txt and try again.

Thanks!

**Comment by seisvelas** [comment]
(For the curious, see https://github.com/python-pillow/Pillow/issues/4896 for how/when this was fixed in Pillow and what caused it)

**Comment by tomholub** [comment]
that fixed it, thanks!

**Comment by kunalbathija** [comment]
Hi, I am still facing same issue, I am on latest version 8.4.0
